import type { Locale } from '../core/i18n'

const en = {
  nav: {
    tryDemo: 'Try demo',
    reviewOwn: 'Review your text',
    github: 'GitHub',
    home: 'Home',
    switchLocale: '中文',
    docs: 'Docs',
    faq: 'FAQ',
    roadmap: 'Roadmap',
  },
  landing: {
    hero: 'See what changes when your evidence changes.',
    sub: 'Trace research claims to source passages, record reviews, and see which claims need another look when a source changes.',
    alphaLine: 'v0.1 alpha - runs in your browser - no account, no upload',
    demosTitle: 'Synthetic demos',
    demosNote: 'All demo studies are invented. They show the mechanics, not real evidence.',
    ownTitle: 'Or start with your own paragraph',
    ownText: 'Paste a paragraph, split it into claims, add the source text you are checking against, bind passages, and record your review. Everything stays in this browser tab until you export a JSON file or an HTML report.',
    scenarioTitle: 'A concrete scenario',
    scenario:
      'You wrote five sentences based on three sources. Weeks later the first source publishes a correction. Which sentences did you build on it, directly or through your own reasoning? Which reviews are now stale, and what did you decide last time? Inspector keeps the passage, the review, and the dependency together so the answer is visible instead of remembered.',
    howTitle: 'How it works',
    how: [
      'Claims and source texts are versioned. Editing creates a new version; old versions stay.',
      'A claim is bound to a passage of a specific source version by character position.',
      'A review records a label, a rationale, and exactly which versions it was based on.',
      'Dependencies between claims are explicit and confirmed by you. Only confirmed links propagate.',
      'When a source or claim changes, affected claims are marked "needs re-review". Verdicts are never flipped automatically.',
    ],
    boundariesTitle: 'What it does not do',
    boundaries: [
      'It does not judge whether a passage truly supports a claim. You do; it records your judgement against a version.',
      'It does not verify DOIs or fetch papers. Identifiers are stored as user-provided.',
      'No PDF import, no AI reading, no database, no collaboration server in v0.1.',
      'Content hashes show whether text changed. They say nothing about truth or authorship.',
    ],
    privacy: 'Your text is processed in the browser. The app makes no network requests after loading. Exporting creates a local file; nothing is shared unless you share it.',
    footer: 'MIT-licensed open source. Alpha software: expect rough edges and report them.',
  },
  ws: {
    syntheticBadge: 'Synthetic demo',
    newWorkspaceTitle: 'My review',
    exportJson: 'Export JSON',
    exportReport: 'Export HTML report',
    importJson: 'Import JSON',
    importError: 'Import refused',
    newWorkspace: 'New workspace',
    confirmDiscard: 'Discard the current workspace? Export it first if you want to keep it.',
    tabs: { claims: 'Claims', source: 'Sources', review: 'Review', history: 'History' },
    guideTitle: 'Demo guide',
    guideCorrection: [
      'Select C1 and look at the passage it is bound to in source A.',
      'In Sources, choose "Synthetic cohort report A", click "Revise source", then "Load suggested correction" and save.',
      'Read the impact banner: which claims are affected and by which path.',
      'Select C1: bind a passage from version 2 and record a new review. The old review stays in history.',
    ],
    guideScope: [
      'Select S2 and read the rationale: population, outcome and causal wording are each checked against the bound passage.',
      'Compare with S1 and S3, which stay inside the source’s scope.',
    ],
    guideMissing: [
      'Select M2 and open its review history: the first verdict was "Cannot determine" because no material existed.',
      'Appendix F was added later, a passage was bound, and a new review was recorded. Both records remain.',
    ],
    // Claims pane
    claims: 'Claims',
    addClaims: 'Add claims',
    addClaimsPlaceholder: 'Paste a paragraph or a single sentence...',
    addAsOne: 'Add as one claim',
    splitAndAdd: 'Split into sentences and add',
    importText: 'Import .txt / .md',
    noClaims: 'No claims yet.',
    selectedClaim: 'Selected claim',
    labelField: 'Label',
    claimText: 'Claim text',
    saveClaimText: 'Save as new version',
    claimUnchanged: 'No change.',
    dependencies: 'Dependencies',
    dependsOn: 'depends on',
    addDependency: 'Add dependency',
    depStatus: { confirmed: 'confirmed', unconfirmed: 'unconfirmed' },
    confirm: 'Confirm',
    remove: 'Remove',
    noDependencies: 'No dependencies recorded.',
    dependedOnBy: 'Depended on by',
    chooseClaim: 'Choose a claim...',
    // Source pane
    sources: 'Sources',
    addSource: 'Add source',
    cancel: 'Cancel',
    sourceTitle: 'Title',
    sourceDoi: 'DOI (optional)',
    sourceUrl: 'URL (optional)',
    sourceText: 'Source text',
    saveSource: 'Save source',
    noSources: 'No sources yet. Add the text you are checking claims against.',
    unverified: 'user-provided, not verified',
    version: 'Version',
    hash: 'SHA-256',
    reviseSource: 'Revise source',
    reviseHint: 'Paste the corrected or updated text. The previous version is kept unchanged.',
    revisionNote: 'Note (optional)',
    saveRevision: 'Save as new version',
    loadSuggested: 'Load suggested correction',
    sameText: 'Text is identical to the current version; nothing saved.',
    selectionHint: 'Select text above to bind it to the selected claim.',
    bindSelection: 'Bind selection to',
    selectClaimFirst: 'Select a claim to bind passages.',
    boundHere: 'Bound to the selected claim',
    viewingOld: 'Viewing an older version. Bindings are made on the version shown.',
    rename: 'Rename',
    // Impact banner
    impactTitle: 'Impact of revision',
    direct: 'Directly affected (bound to this source)',
    indirect: 'Indirectly affected (confirmed dependency)',
    potential: 'Potential only (through an unconfirmed dependency; not propagated)',
    unaffected: 'Not affected by this change',
    none: 'none',
    dismiss: 'Dismiss',
    // Review pane
    review: 'Review',
    selectClaimHint: 'Select a claim to review it.',
    state: 'State',
    reasons: 'Why re-review is needed',
    boundPassages: 'Bound passages',
    supersededPassages: 'Superseded bindings (older source version)',
    findInCurrent: 'Find this passage in the current version',
    rebindAt: 'Re-bind at',
    notFound: 'Passage not found exactly once in the current version. Select it manually in the source pane.',
    noBindingsYet: 'No passage bound yet. "Cannot determine" is the honest label when material is missing.',
    recordReview: 'Record review for version',
    rationale: 'Rationale',
    rationalePlaceholder: 'What in the passage supports or contradicts the claim? Note scope: population, time, outcome, wording.',
    reviewer: 'Reviewer (optional)',
    submitReview: 'Record review',
    rationaleRequired: 'A rationale is required.',
    reviewHistory: 'Review history',
    basedOn: 'based on',
    claimVersions: 'Claim versions',
    history: 'History',
    noHistory: 'Nothing yet.',
    current: 'current',
    latest: 'latest',
    stateNote: 'Labels are human judgements about a specific version. "Needs re-review" means the basis changed; it does not flip the verdict.',
  },
}

export type UIStrings = typeof en

const zhCN: UIStrings = {
  nav: {
    tryDemo: '试用示例',
    reviewOwn: '审阅自己的文字',
    github: 'GitHub',
    home: '首页',
    switchLocale: 'English',
    docs: '文档',
    faq: '常见问题',
    roadmap: '路线图',
  },
  landing: {
    hero: '看清证据变化时，什么会跟着变。',
    sub: '把研究主张定位到来源原文片段，记录人工审阅；来源改变时，看出哪些主张需要重新审核。',
    alphaLine: 'v0.1 alpha · 在浏览器内运行 · 无需账号，不上传资料',
    demosTitle: '合成演示',
    demosNote: '演示里的"研究"全部是虚构的，只用于展示机制，不代表真实证据。',
    ownTitle: '或者从你自己的段落开始',
    ownText: '粘贴一段文字，切分成主张；加入你要核对的来源文本，绑定片段，记录审阅。所有内容留在当前浏览器标签页，直到你导出 JSON 文件或 HTML 报告。',
    scenarioTitle: '一个具体场景',
    scenario:
      '你根据三篇来源写了五句话。几周后，第一篇来源发布更正。哪些句子直接或经由你自己的推理建立在它上面？哪些审阅已经失效？上次你是怎么判的？Inspector 把片段、审阅和依赖关系放在一起，答案是可见的，而不是靠记忆。',
    howTitle: '工作方式',
    how: [
      '主张和来源文本都有版本。修改会产生新版本，旧版本保留。',
      '主张按字符位置绑定到某个来源版本的片段。',
      '审阅记录标签、理由，以及当时依据的具体版本。',
      '主张之间的依赖关系由你显式添加并确认；只有已确认的关系会传播。',
      '来源或主张变化时，受影响的主张标为"需复核"。结论从不被自动反转。',
    ],
    boundariesTitle: '它不做什么',
    boundaries: [
      '它不判断片段是否真的支持主张。判断由你做出；它把判断与版本一起记录。',
      '它不验证 DOI，也不抓取论文。标识符按"用户提供"保存。',
      'v0.1 没有 PDF 导入、AI 阅读、数据库或协作服务器。',
      '内容哈希只说明文本是否变化，不说明真实性或作者身份。',
    ],
    privacy: '你的文字在浏览器内处理。应用加载后不发起任何网络请求。导出只生成本地文件；除非你自己分享，否则不会传给任何人。',
    footer: 'MIT 许可的开源软件。Alpha 版本：会有粗糙之处，欢迎反馈。',
  },
  ws: {
    syntheticBadge: '合成演示',
    newWorkspaceTitle: '我的审阅',
    exportJson: '导出 JSON',
    exportReport: '导出 HTML 报告',
    importJson: '导入 JSON',
    importError: '导入被拒绝',
    newWorkspace: '新建工作区',
    confirmDiscard: '放弃当前工作区？如需保留请先导出。',
    tabs: { claims: '主张', source: '来源', review: '审阅', history: '历史' },
    guideTitle: '演示指引',
    guideCorrection: [
      '选中 C1，查看它在来源 A 中绑定的片段。',
      '在"来源"里选择 "Synthetic cohort report A"，点击"修订来源"，再点"载入建议的更正"并保存。',
      '阅读影响提示：哪些主张受影响、经由什么路径。',
      '选中 C1：从第 2 版绑定片段并记录新的审阅。旧审阅保留在历史中。',
    ],
    guideScope: ['选中 S2 阅读理由：人群、结局和因果措辞逐项对照绑定片段核查。', '对比 S1 与 S3，它们停留在来源所述范围内。'],
    guideMissing: ['选中 M2 打开审阅历史：第一次判定是"无法判断"，因为当时没有材料。', '之后加入了附录 F，绑定片段并记录了新的审阅。两条记录都保留。'],
    claims: '主张',
    addClaims: '添加主张',
    addClaimsPlaceholder: '粘贴一段文字或一句话……',
    addAsOne: '作为一条主张添加',
    splitAndAdd: '切分为句子后添加',
    importText: '导入 .txt / .md',
    noClaims: '还没有主张。',
    selectedClaim: '当前主张',
    labelField: '标签',
    claimText: '主张文本',
    saveClaimText: '保存为新版本',
    claimUnchanged: '没有变化。',
    dependencies: '依赖关系',
    dependsOn: '依赖于',
    addDependency: '添加依赖',
    depStatus: { confirmed: '已确认', unconfirmed: '未确认' },
    confirm: '确认',
    remove: '移除',
    noDependencies: '未记录依赖关系。',
    dependedOnBy: '被以下主张依赖',
    chooseClaim: '选择主张……',
    sources: '来源',
    addSource: '添加来源',
    cancel: '取消',
    sourceTitle: '标题',
    sourceDoi: 'DOI（可选）',
    sourceUrl: 'URL（可选）',
    sourceText: '来源文本',
    saveSource: '保存来源',
    noSources: '还没有来源。加入你要核对主张的文本。',
    unverified: '用户提供，未验证',
    version: '版本',
    hash: 'SHA-256',
    reviseSource: '修订来源',
    reviseHint: '粘贴更正或更新后的文本。之前的版本原样保留。',
    revisionNote: '备注（可选）',
    saveRevision: '保存为新版本',
    loadSuggested: '载入建议的更正',
    sameText: '文本与当前版本相同，未保存。',
    selectionHint: '在上方选中文本，可将其绑定到当前主张。',
    bindSelection: '将选中片段绑定到',
    selectClaimFirst: '先选择一条主张，再绑定片段。',
    boundHere: '已绑定到当前主张',
    viewingOld: '正在查看旧版本。绑定作用于所显示的版本。',
    rename: '改名',
    impactTitle: '本次修订的影响',
    direct: '直接受影响（绑定到该来源）',
    indirect: '间接受影响（经已确认的依赖）',
    potential: '仅潜在影响（经未确认的依赖；不传播）',
    unaffected: '不受本次变更影响',
    none: '无',
    dismiss: '关闭',
    review: '审阅',
    selectClaimHint: '选择一条主张进行审阅。',
    state: '状态',
    reasons: '需要复核的原因',
    boundPassages: '绑定片段',
    supersededPassages: '已被取代的绑定（旧来源版本）',
    findInCurrent: '在当前版本中查找该片段',
    rebindAt: '重新绑定于',
    notFound: '在当前版本中未能唯一找到该片段。请在来源面板中手动选择。',
    noBindingsYet: '尚未绑定片段。材料缺失时，"无法判断"才是诚实的标签。',
    recordReview: '记录针对以下版本的审阅：版本',
    rationale: '理由',
    rationalePlaceholder: '片段中哪些内容支持或反驳主张？注意范围：人群、时间、结局、措辞。',
    reviewer: '审阅者（可选）',
    submitReview: '记录审阅',
    rationaleRequired: '必须填写理由。',
    reviewHistory: '审阅历史',
    basedOn: '依据',
    claimVersions: '主张版本',
    history: '历史',
    noHistory: '暂无记录。',
    current: '当前',
    latest: '最新',
    stateNote: '标签是针对具体版本的人工判断。"需复核"表示依据发生了变化，并不反转结论。',
  },
}

export const UI: Record<Locale, UIStrings> = { en, 'zh-CN': zhCN }
